name = "mongo-realm-worker"
type = "javascript"
compatibility_date = "2023-09-28"
account_id = "acf1282ce46a76893a4e6669f9cc83a1"
workers_dev = true # or zone_id = "<ZONE ID>" if you have one

[build]
command = "npm run build"

[build.upload]
dir = "build"
main = "./index.mjs"
format = "modules"

[vars]
REALM_APPID = "cloudflare-gpjvf"
